const revealItems = document.querySelectorAll(".reveal");

const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add("show");
        observer.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.2 }
);

revealItems.forEach((item) => observer.observe(item));

const translations = {
  en: {
    "nav.download": "Download",
    "nav.how": "How it works",
    "nav.security": "Security",
    "nav.platforms": "Platforms",
    "nav.langLabel": "Language",
    "hero.eyebrow": "Fast, private file handoffs",
    "hero.title": "Send a file with a short code, not a long link.",
    "hero.lead":
      "Pushcode makes sharing feel simple and safe. Create a six-character code, share it, and your file arrives securely. Senders sign in, and only your device can open the file.",
    "hero.ctaPrimary": "Open the web app",
    "hero.ctaSecondary": "Download the apps",
    "hero.meta1Label": "Short-lived",
    "hero.meta1Value": "Codes expire fast",
    "hero.meta2Label": "Easy to share",
    "hero.meta2Value": "Six characters",
    "hero.meta3Label": "Works everywhere",
    "hero.meta3Value": "iOS · iPadOS · macOS · Windows · Linux CLI · Web",
    "hero.status1Title": "Waiting for the file",
    "hero.status1Body": "The sender signs in and uploads using your code.",
    "hero.status2Title": "Locked before it leaves",
    "hero.status2Body": "Your file stays private from start to finish.",
    "hero.status3Title": "Ready when you are",
    "hero.status3Body": "Download once, then it is gone.",
    "hero.tileLabel": "ACTIVE PUSHCODE",
    "hero.tileNote": "Tap to copy · expires in 58:14",
    "download.title": "Get Pushcode on every device.",
    "download.subtitle": "Download the apps so you are ready the moment a file arrives.",
    "download.iosLabel": "iOS & iPadOS",
    "download.iosTitle": "Download on the App Store",
    "download.iosNote": "Requires iOS 16.6 / iPadOS 16.6+",
    "download.macLabel": "macOS",
    "download.macTitle": "Download for Mac",
    "download.macNote": "Requires macOS 13.5 Ventura+",
    "download.winLabel": "Windows",
    "download.winTitle": "Download for Windows",
    "download.winNote": "Requires Windows 10+",
    "download.beta": "BETA",
    "download.cta": "Download",
    "download.linuxLabel": "Linux CLI",
    "download.linuxTitle": "Install the CLI",
    "download.linuxNote": "x86_32 · amd64 · arm64",
    "download.webLabel": "Web",
    "download.webTitle": "Open in the browser",
    "download.open": "Open",
    "download.webNote": "Sending only (no receiving)",
    "download.androidLabel": "Android",
    "download.androidTitle": "Coming soon",
    "download.androidNote": "Join the waitlist for early access",
    "download.select": "Select",
    "download.macSelect": "Mac download options",
    "download.macIntel": "Intel",
    "download.macApple": "Apple Silicon",
    "download.winSelect": "Windows download options",
    "download.win32": "32-bit",
    "download.win64": "64-bit",
    "download.linuxSelect": "Linux CLI download options",
    "download.linuxX86": "x86_32",
    "download.linuxAmd64": "amd64",
    "download.linuxArm64": "arm64",
    "how.title": "How it works (technical).",
    "how.subtitle":
      "Sender authenticates, fetches the receiver public key, encrypts the file locally, and uploads the encrypted container. The owner downloads and decrypts using their device key; the server never sees plaintext.",
    "how.step1Title": "Create pushcode + key",
    "how.step1Body": "The owner creates a pushcode bound to a device public key and short TTL.",
    "how.step2Title": "Encrypt & upload",
    "how.step2Body":
      "Sender authenticates, fetches the public key, encrypts the file locally, and uploads the encrypted container.",
    "how.step3Title": "Owner decrypts",
    "how.step3Body":
      "Owner downloads the container and decrypts with their device key; transfer closes after download or TTL.",
    "security.title": "Built for trust.",
    "security.subtitle": "Plain-English privacy that feels easy.",
    "security.card1Title": "Private by default",
    "security.card1Body": "Your files are locked before they leave your device.",
    "security.card1Tag": "Private",
    "security.card2Title": "Short-lived access",
    "security.card2Body": "Codes expire quickly, so old links do not hang around.",
    "security.card2Tag": "Short-lived",
    "security.card3Title": "Only the owner can open",
    "security.card3Body": "The file opens only on the device that made the code.",
    "security.card3Tag": "Owner-only",
    "security.card4Title": "Protected from guessing",
    "security.card4Body": "We block repeated guessing attempts.",
    "security.card4Tag": "Protection",
    "security.note":
      "In short: even if someone finds your code, they still cannot open the file without your device. It is designed to keep private stuff private.",
    "platforms.title": "Everywhere you work.",
    "platforms.subtitle": "Fast, simple apps built for each device.",
    "platforms.iosTitle": "iOS & iPadOS",
    "platforms.iosBody": "Quick sharing with a clean, mobile-first design.",
    "platforms.macTitle": "macOS",
    "platforms.macBody": "A lightweight menu-bar app for instant access.",
    "platforms.winTitle": "Windows",
    "platforms.winBody": "Tray-friendly, fast, and ready for daily work.",
    "platforms.linuxTitle": "Linux CLI",
    "platforms.linuxBody": "Scriptable transfers for terminals and CI.",
    "platforms.webTitle": "Web",
    "platforms.webBody": "Use it anywhere without installing anything.",
    "api.title": "How it works (technical).",
    "api.subtitle":
      "Files are encrypted on the sender’s device, uploaded as encrypted containers, and can only be opened by the owner’s device key.",
    "api.cardTitle": "Reliable, predictable transfers",
    "api.point1": "Short codes keep sharing effortless.",
    "api.point2": "Sender sign-in for accountability.",
    "api.point3": "Owner-only access to downloads.",
    "api.point4": "Works across desktop and mobile.",
    "api.cta": "Read the docs",
    "api.noteLabel": "Working description (for technical readers)",
    "api.noteBody":
      "Pushcode is an end-to-end encrypted file handoff system with short-lived codes, sender authentication, and owner-only downloads.",
    "cta.title": "Ready to share with confidence?",
    "cta.subtitle": "Join the private beta and start sending across all platforms.",
    "cta.primary": "Request access",
    "cta.secondary": "Talk to us",
    "privacy.navHome": "Home",
    "privacy.navPrivacy": "Privacy",
    "terms.navTerms": "Terms",
    "terms.navFairUse": "Fair Use",
    "terms.title": "Terms of Service — Pushcode",
    "terms.lastUpdated": "Last updated: January 20, 2026",
    "terms.section1Title": "1. About these Terms",
    "terms.section1Body": "These Terms of Service (“Terms”) govern your access to and use of the Pushcode applications, APIs, and related services (the “Service”). By creating an account, using the Service, or uploading/downloading an artifact, you agree to these Terms.",
    "terms.section2Title": "2. Service description (high-level)",
    "terms.section2Body": "Pushcode enables end‑to‑end encrypted file transfers using short‑lived “pushcodes.” The sender encrypts a file locally and uploads a binary encrypted container (“artifact”) to the Service. Only the intended recipient (“Owner”)—who holds the corresponding private key on their device—can download and decrypt the artifact.",
    "terms.section3Title": "3. Eligibility",
    "terms.section3Body": "You must be at least 16 years old and capable of entering into a binding agreement. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization.",
    "terms.section4Title": "4. Accounts and authentication",
    "terms.section4Body": "Owners use an email address and password to create an account. Passwords are stored only as a secure hash. The Service uses access tokens and refresh tokens to maintain sessions. You are responsible for maintaining account security and all activity under your account and must notify us promptly of unauthorized access.",
    "terms.section5Title": "5. Pushcodes, access model, and rate limits",
    "terms.section5A": "Pushcodes are short‑lived (default TTL 1 hour; configurable) and coordinate a transfer.",
    "terms.section5B": "Uploading an artifact does not require an account login; a valid pushcode acts as a bearer token.",
    "terms.section5C": "Downloading an artifact requires the Owner to be authenticated; only the Owner may download/delete artifacts.",
    "terms.section5D": "Rate limits (per IP and per user) apply to prevent brute‑force guessing and abuse.",
    "terms.section6Title": "6. Your content, responsibilities, and acceptable use",
    "terms.section6A": "You are responsible for the content you upload, share, or receive via the Service (“User Content”).",
    "terms.section6B": "You may not use the Service to violate law, infringe rights, distribute malware/phishing/spam, guess pushcodes, bypass rate limits, or interfere with the Service.",
    "terms.section6C": "Avoid uploading highly sensitive data unless you accept the risks of device compromise and operational exposure.",
    "terms.section7Title": "7. Encryption, keys, and limitations of confidentiality",
    "terms.section7A": "Artifacts are encrypted using AES‑256‑GCM; file keys are wrapped via X25519 + HKDF‑SHA256 + ChaCha20‑Poly1305.",
    "terms.section7B": "Private keys remain on device. If you lose your private key, you may permanently lose access to encrypted artifacts.",
    "terms.section7C": "We do not decrypt artifacts in normal operation. Confidentiality also depends on your device security and handling of pushcodes and decrypted files.",
    "terms.section8Title": "8. Service limits and storage",
    "terms.section8A": "Artifacts are subject to size limits (MVP: max 100MB per artifact) and may be rejected if too large.",
    "terms.section8B": "Pushcodes and artifacts expire based on TTL and lifecycle state; expired data may be deleted automatically.",
    "terms.section8C": "We may modify, suspend, or discontinue parts of the Service at any time and do not guarantee uninterrupted availability.",
    "terms.section9Title": "9. Intellectual property",
    "terms.section9Body": "We and our licensors own all rights in the Service, including software, trademarks, and documentation. You receive a limited, non‑exclusive, non‑transferable right to use the Service in accordance with these Terms.",
    "terms.section10Title": "10. Termination",
    "terms.section10Body": "You may stop using the Service at any time. We may suspend or terminate access if you violate these Terms, if required by law, or to protect the Service and other users.",
    "terms.section11Title": "11. Disclaimers",
    "terms.section11Body": "The Service is provided “as is” and “as available.” To the maximum extent permitted by law, we disclaim all warranties. We do not warrant uninterrupted service or that artifacts will always be retrievable (e.g., after expiration, deletion, or key loss).",
    "terms.section12Title": "12. Limitation of liability",
    "terms.section12Body": "To the maximum extent permitted by law, dolani GmbH shall not be liable for indirect, incidental, special, consequential, or punitive damages, or for loss of data, profits, revenue, or business. Our total liability is limited to the amount you paid to use the Service in the 12 months prior to the event giving rise to liability, or CHF 100, whichever is greater, unless mandatory law requires otherwise.",
    "terms.section13Title": "13. Indemnification",
    "terms.section13Body": "If you use the Service on behalf of a business, you agree to indemnify and hold harmless dolani GmbH from claims arising out of your User Content or your breach of these Terms.",
    "terms.section14Title": "14. Governing law and venue",
    "terms.section14Body": "These Terms are governed by the laws of Switzerland. Courts located in Zürich shall have exclusive jurisdiction, unless mandatory consumer law provides otherwise.",
    "terms.section15Title": "15. Changes to these Terms",
    "terms.section15Body": "We may update these Terms from time to time. The “Last updated” date indicates the latest version. Continued use after changes becomes effective constitutes acceptance.",
    "terms.section16Title": "16. Contact",
    "terms.section16Body": "dolani GmbH, Kolbenacker 14, 8052 Zürich, Switzerland. Email: compliance@dolani.ch",
    "fair.title": "Fair Use",
    "fair.subtitle": "Keep Pushcode fast and reliable for everyone.",
    "fair.generalTitle": "General Guidelines",
    "fair.generalBody": "Pushcode is designed for short‑lived, person‑to‑person transfers. Please avoid using it as a bulk file hosting or long‑term storage service.",
    "fair.abuseTitle": "Abuse Prevention",
    "fair.abuseBody": "Automated scraping, brute‑force attempts, or abuse of rate limits may result in temporary or permanent blocks.",
    "fair.limitsTitle": "Reasonable Limits",
    "fair.limitsBody": "We may enforce limits on uploads, requests, or bandwidth to keep the service stable for everyone.",
    "privacy.title": "Privacy Information",
    "privacy.subtitle": "Privacy Information for Pushcode",
    "privacy.lastUpdated": "Last updated: January 20, 2026",
    "privacy.section1Title": "1. Controller",
    "privacy.controllerBody": "The controller responsible for processing your personal data is: dolani GmbH, Kolbenacker 14, 8052 Zürich, Switzerland. Email: compliance@dolani.ch",
    "privacy.dpoBody": "DPO contact: compliance@dolani.ch",
    "privacy.section2Title": "2. What Pushcode is and how it works (privacy perspective)",
    "privacy.section2Body": "Pushcode enables end‑to‑end encrypted file transfers using short‑lived “pushcodes”. The server stores only the encrypted file container (“artifact”) and limited metadata required to operate the service. The service is designed to minimize metadata (e.g., no filename or MIME type is included in the container header by default).",
    "privacy.section3Title": "3. Categories of personal data we process",
    "privacy.section3A": "A. Account & authentication data (registered users / “owners”)",
    "privacy.section3A1": "Email address",
    "privacy.section3A2": "Password hash (we do not store plaintext passwords)",
    "privacy.section3A3": "Session / token data (e.g., access and refresh tokens; device identifier if provided)",
    "privacy.section3A4": "Email verification status and timestamps",
    "privacy.section3B": "B. Pushcode session & cryptographic metadata",
    "privacy.section3B1": "Pushcode value (6 characters) and expiry time (TTL)",
    "privacy.section3B2": "Recipient/owner reference (user ID)",
    "privacy.section3B3": "Recipient public key (X25519 public key)",
    "privacy.section3B4": "Status timestamps (created / expires / downloaded)",
    "privacy.section3C": "C. Encrypted content (“artifact”)",
    "privacy.section3C1": "Encrypted file container (ciphertext) stored on our infrastructure until deleted or expired",
    "privacy.section3C2": "Container header elements required for decryption by the recipient (e.g., ephemeral public key, wrapped key, nonces, file size, tag). These elements do not allow decryption without the recipient’s private key.",
    "privacy.section3D": "D. Technical and security data",
    "privacy.section3D1": "IP address and request metadata for rate limiting, fraud prevention, and security logging",
    "privacy.section3D2": "Request IDs / logs (where enabled)",
    "privacy.section4Title": "4. Purposes and legal bases (GDPR, where applicable)",
    "privacy.section4A": "Providing the service (account, pushcodes, artifact transfer) — Art. 6(1)(b) GDPR",
    "privacy.section4B": "Security, abuse prevention, and service integrity — Art. 6(1)(f) GDPR and/or Art. 6(1)(c)",
    "privacy.section4C": "Operational communications (e.g., verification emails, security notices) — Art. 6(1)(b) and/or Art. 6(1)(f)",
    "privacy.section4D": "Compliance and defense of legal claims — Art. 6(1)(f) and/or Art. 6(1)(c)",
    "privacy.section5Title": "5. Data retention",
    "privacy.section5A": "Pushcodes and related metadata: stored until expiration (default TTL 1 hour; configurable 5 minutes to 24 hours) or deletion by the owner.",
    "privacy.section5B": "Encrypted artifacts: stored until deleted by the owner, expired by TTL, or removed by cleanup processes after download/expiration.",
    "privacy.section5C": "Account data: stored as long as your account is active and as needed for legal compliance.",
    "privacy.section5D": "Security logs / rate limiting data: retained for as long as necessary to protect the service and investigate abuse (typically up to 30 days).",
    "privacy.section6Title": "6. Recipients and sharing",
    "privacy.section6A": "Hosting and infrastructure providers acting as processors on our instructions",
    "privacy.section6B": "Email delivery providers (for verification / service emails), if used",
    "privacy.section6C": "Authorities / advisors where legally required or necessary for legal defense",
    "privacy.section6Note": "We do not share or sell the contents of your files. The server stores encrypted artifacts only and cannot decrypt them without the recipient’s private key.",
    "privacy.section7Title": "7. International transfers",
    "privacy.section7Body": "If data is transferred outside the EEA/UK/Switzerland, we rely on appropriate safeguards (e.g., Standard Contractual Clauses) where required. Details are available upon request.",
    "privacy.section8Title": "8. Security",
    "privacy.section8A": "End‑to‑end encryption design: private keys remain on device (Keychain/DPAPI depending on platform)",
    "privacy.section8B": "Authenticated encryption for artifacts and wrapped keys (AES‑GCM, ChaCha20‑Poly1305)",
    "privacy.section8C": "Strong password hashing (Argon2id) and short‑lived access tokens",
    "privacy.section8D": "Rate limiting to prevent pushcode guessing and abuse",
    "privacy.section8E": "Owner‑only authenticated download of artifacts",
    "privacy.section9Title": "9. Your rights",
    "privacy.section9Body": "Subject to applicable law, you may have the right to access, rectification, erasure, restriction, portability, and objection; to withdraw consent where applicable; and to lodge a complaint with a supervisory authority. To exercise your rights, contact compliance@dolani.ch.",
    "privacy.section10Title": "10. Children",
    "privacy.section10Body": "Pushcode is not intended for children under the age of 16. We do not knowingly collect children’s data.",
    "privacy.section11Title": "11. Changes",
    "privacy.section11Body": "We may update this Privacy Information from time to time. The “Last updated” date will reflect changes.",
    "footer.tagline": "Secure file sharing for individuals.",
    "footer.brandPrefix": "pushcode.io is a product of",
    "footer.brandLink": "dolani GmbH",
    "footer.copyright": "© 2025 dolani GmbH - from Tsüri🇨🇭 with ❤️",
    "footer.availability": "Available on iOS, iPadOS, macOS, Windows, Linux CLI, and web."
  },
  de: {
    "nav.download": "Download",
    "nav.how": "So funktioniert es",
    "nav.security": "Sicherheit",
    "nav.platforms": "Plattformen",
    "nav.langLabel": "Sprache",
    "hero.eyebrow": "Schnelle, private Dateifreigaben",
    "hero.title": "Dateien per kurzem Code senden, nicht per langem Link.",
    "hero.lead":
      "Pushcode macht das Teilen einfach und sicher. Erstelle einen sechsstelligen Code, teile ihn, und die Datei kommt geschützt an. Absender melden sich an, und nur dein Gerät kann sie öffnen.",
    "hero.ctaPrimary": "Web-App öffnen",
    "hero.ctaSecondary": "Apps herunterladen",
    "hero.meta1Label": "Kurzlebig",
    "hero.meta1Value": "Codes verfallen schnell",
    "hero.meta2Label": "Leicht zu teilen",
    "hero.meta2Value": "Sechs Zeichen",
    "hero.meta3Label": "Überall nutzbar",
    "hero.meta3Value": "iOS · iPadOS · macOS · Windows · Linux-CLI · Web",
    "hero.status1Title": "Warten auf die Datei",
    "hero.status1Body": "Der Absender meldet sich an und lädt mit deinem Code hoch.",
    "hero.status2Title": "Vor dem Senden gesperrt",
    "hero.status2Body": "Deine Datei bleibt von Anfang bis Ende privat.",
    "hero.status3Title": "Bereit, wenn du es bist",
    "hero.status3Body": "Einmal herunterladen, dann ist sie weg.",
    "hero.tileLabel": "AKTIVER PUSHCODE",
    "hero.tileNote": "Tippen zum Kopieren · läuft ab in 58:14",
    "download.title": "Pushcode auf jedem Gerät.",
    "download.subtitle": "Lade die Apps, damit du bereit bist, sobald eine Datei ankommt.",
    "download.iosLabel": "iOS & iPadOS",
    "download.iosTitle": "Im App Store laden",
    "download.iosNote": "Erfordert iOS 16.6 / iPadOS 16.6+",
    "download.macLabel": "macOS",
    "download.macTitle": "Für Mac laden",
    "download.macNote": "Erfordert macOS 13.5 Ventura+",
    "download.winLabel": "Windows",
    "download.winTitle": "Für Windows laden",
    "download.winNote": "Erfordert Windows 10+",
    "download.beta": "BETA",
    "download.cta": "Laden",
    "download.linuxLabel": "Linux-CLI",
    "download.linuxTitle": "CLI installieren",
    "download.linuxNote": "x86_32 · amd64 · arm64",
    "download.webLabel": "Web",
    "download.webTitle": "Im Browser öffnen",
    "download.open": "Öffnen",
    "download.webNote": "Nur Versand (kein Empfang)",
    "download.androidLabel": "Android",
    "download.androidTitle": "Demnächst",
    "download.androidNote": "Auf die Warteliste für Early Access",
    "download.select": "Auswählen",
    "download.macSelect": "Mac-Download-Optionen",
    "download.macIntel": "Intel",
    "download.macApple": "Apple Silicon",
    "download.winSelect": "Windows-Download-Optionen",
    "download.win32": "32-Bit",
    "download.win64": "64-Bit",
    "download.linuxSelect": "Linux-CLI-Optionen",
    "download.linuxX86": "x86_32",
    "download.linuxAmd64": "amd64",
    "download.linuxArm64": "arm64",
    "how.title": "So funktioniert es (technisch).",
    "how.subtitle":
      "Absender authentifiziert sich, holt den öffentlichen Schlüssel des Empfängers, verschlüsselt lokal und lädt den verschlüsselten Container hoch. Der Besitzer lädt herunter und entschlüsselt mit dem Geräteschlüssel; der Server sieht keinen Klartext.",
    "how.step1Title": "Pushcode + Schlüssel",
    "how.step1Body": "Der Besitzer erstellt einen Pushcode mit Geräte‑Public‑Key und kurzer TTL.",
    "how.step2Title": "Verschlüsseln & hochladen",
    "how.step2Body":
      "Absender authentifiziert sich, holt den Public Key, verschlüsselt lokal und lädt den Container hoch.",
    "how.step3Title": "Besitzer entschlüsselt",
    "how.step3Body":
      "Besitzer lädt den Container herunter und entschlüsselt mit dem Geräteschlüssel; Abschluss nach Download oder TTL.",
    "security.title": "Für Vertrauen gebaut.",
    "security.subtitle": "Datenschutz in Klartext.",
    "security.card1Title": "Standardmäßig privat",
    "security.card1Body": "Dateien werden gesperrt, bevor sie dein Gerät verlassen.",
    "security.card1Tag": "Privat",
    "security.card2Title": "Kurzlebiger Zugriff",
    "security.card2Body": "Codes laufen schnell ab - keine alten Links.",
    "security.card2Tag": "Kurzlebig",
    "security.card3Title": "Nur der Besitzer öffnet",
    "security.card3Body": "Die Datei öffnet nur auf dem Gerät, das den Code erstellt hat.",
    "security.card3Tag": "Nur Besitzer",
    "security.card4Title": "Schutz vor Raten",
    "security.card4Body": "Wiederholtes Raten wird blockiert.",
    "security.card4Tag": "Schutz",
    "security.note":
      "Kurz gesagt: Selbst wenn jemand deinen Code findet, kann er die Datei ohne dein Gerät nicht öffnen. Privat bleibt privat.",
    "platforms.title": "Überall, wo du arbeitest.",
    "platforms.subtitle": "Schnelle, einfache Apps für jedes Gerät.",
    "platforms.iosTitle": "iOS & iPadOS",
    "platforms.iosBody": "Schnelles Teilen mit klarem, mobilem Design.",
    "platforms.macTitle": "macOS",
    "platforms.macBody": "Leichte Menüleisten-App für sofortigen Zugriff.",
    "platforms.winTitle": "Windows",
    "platforms.winBody": "Schnell, zuverlässig, ideal für den Alltag.",
    "platforms.linuxTitle": "Linux-CLI",
    "platforms.linuxBody": "Skriptfähig für Terminal und CI.",
    "platforms.webTitle": "Web",
    "platforms.webBody": "Überall nutzbar, ohne Installation.",
    "api.title": "So funktioniert es (technisch).",
    "api.subtitle":
      "Dateien werden auf dem Gerät des Absenders verschlüsselt, als verschlüsselte Container hochgeladen und können nur mit dem Geräteschlüssel des Besitzers geöffnet werden.",
    "api.cardTitle": "Zuverlässige Transfers",
    "api.point1": "Kurze Codes machen das Teilen leicht.",
    "api.point2": "Absender-Login für Verantwortung.",
    "api.point3": "Nur Besitzer können herunterladen.",
    "api.point4": "Funktioniert auf Desktop und Mobil.",
    "api.cta": "Dokumentation",
    "api.noteLabel": "Arbeitsbeschreibung (für Techniker)",
    "api.noteBody":
      "Pushcode ist ein Ende-zu-Ende-verschlüsseltes System für Dateiübergaben mit kurzen Codes, Absender-Login und Besitzer-Downloads.",
    "cta.title": "Bereit, sicher zu teilen?",
    "cta.subtitle": "Tritt der privaten Beta bei und sende auf allen Plattformen.",
    "cta.primary": "Zugang anfordern",
    "cta.secondary": "Kontakt aufnehmen",
    "privacy.navHome": "Start",
    "privacy.navPrivacy": "Datenschutz",
    "terms.navTerms": "Nutzungsbedingungen",
    "terms.navFairUse": "Fair Use",
    "terms.title": "Nutzungsbedingungen — Pushcode",
    "terms.lastUpdated": "Stand: 20. Januar 2026",
    "terms.section1Title": "1. Geltungsbereich",
    "terms.section1Body": "Diese Nutzungsbedingungen („Bedingungen“) regeln die Nutzung der Pushcode Apps, APIs und zugehörigen Dienste („Dienst“). Mit Registrierung oder Nutzung (inkl. Upload/Download eines Artifacts) akzeptierst du diese Bedingungen.",
    "terms.section2Title": "2. Dienstbeschreibung (kurz)",
    "terms.section2Body": "Pushcode ermöglicht Ende‑zu‑Ende verschlüsselte Dateiübertragungen über kurzlebige Pushcodes. Der Sender verschlüsselt lokal und lädt einen verschlüsselten Container („Artifact“) hoch; nur der Empfänger („Owner“) kann den Container herunterladen und entschlüsseln.",
    "terms.section3Title": "3. Teilnahmeberechtigung",
    "terms.section3Body": "Du musst mindestens 16 Jahre alt sein und rechtsfähig sein. Bei Nutzung für ein Unternehmen versicherst du, vertretungsberechtigt zu sein.",
    "terms.section4Title": "4. Konto und Authentifizierung",
    "terms.section4Body": "Owner registrieren sich mit E‑Mail und Passwort; Passwörter werden ausschließlich als sicherer Hash gespeichert. Sessions werden über Access-/Refresh‑Tokens verwaltet. Du bist für die Sicherheit deines Kontos verantwortlich und musst unbefugte Nutzung unverzüglich melden.",
    "terms.section5Title": "5. Pushcodes, Zugriffsmodell, Rate Limits",
    "terms.section5A": "Pushcodes sind kurzlebig (Standard TTL 1 Stunde; konfigurierbar) und koordinieren eine Übertragung.",
    "terms.section5B": "Für den Upload ist keine Anmeldung erforderlich; der Pushcode wirkt als Bearer‑Token.",
    "terms.section5C": "Der Download ist nur für authentifizierte Owner möglich; nur der Owner darf Artifacts löschen/herunterladen.",
    "terms.section5D": "Rate Limits (u. a. per IP/User) schützen vor Bruteforce und Missbrauch; Überschreitungen können zu Sperren führen.",
    "terms.section6Title": "6. Inhalte, Pflichten, zulässige Nutzung",
    "terms.section6A": "Du bist verantwortlich für Inhalte, die du hochlädst, teilst oder empfängst („Nutzerinhalte“).",
    "terms.section6B": "Untersagt ist u. a. rechtswidrige Nutzung, Malware/Phishing/Spam, Pushcode‑Raten, Umgehung von Limits oder Störung des Dienstes.",
    "terms.section6C": "Vermeide das Hochladen hochsensibler Daten, sofern du die Risiken nicht akzeptieren willst.",
    "terms.section7Title": "7. Verschlüsselung, Schlüssel, Grenzen der Vertraulichkeit",
    "terms.section7A": "Verschlüsselung per AES‑256‑GCM; Key‑Wrap via X25519 + HKDF‑SHA256 + ChaCha20‑Poly1305.",
    "terms.section7B": "Private Keys bleiben auf dem Gerät. Bei Verlust kann der Zugriff auf Artifacts dauerhaft verloren gehen.",
    "terms.section7C": "Wir entschlüsseln Artifacts im Normalbetrieb nicht. Vertraulichkeit hängt auch von deiner Gerätesicherheit ab.",
    "terms.section8Title": "8. Limits, Speicherung, Verfügbarkeit",
    "terms.section8A": "Artifacts unterliegen Größenlimits (MVP: max. 100MB); zu große Uploads werden abgelehnt.",
    "terms.section8B": "Pushcodes/Artifacts verfallen gemäß TTL; wir können abgelaufene Daten automatisch löschen.",
    "terms.section8C": "Wir können den Dienst anpassen, aussetzen oder einstellen; ein unterbrechungsfreier Betrieb wird nicht garantiert.",
    "terms.section9Title": "9. Schutzrechte",
    "terms.section9Body": "Alle Rechte am Dienst (Software, Marken, Doku) liegen bei dolani GmbH bzw. Lizenzgebern. Du erhältst ein einfaches, nicht übertragbares Nutzungsrecht gemäß diesen Bedingungen.",
    "terms.section10Title": "10. Sperrung und Kündigung",
    "terms.section10Body": "Du kannst die Nutzung jederzeit beenden. Wir können sperren/kündigen, wenn du gegen diese Bedingungen verstößt, wenn es gesetzlich erforderlich ist oder zur Abwehr von Missbrauch/Sicherheitsrisiken.",
    "terms.section11Title": "11. Gewährleistungsausschluss",
    "terms.section11Body": "Der Dienst wird „wie besehen“ und „wie verfügbar“ bereitgestellt. Soweit gesetzlich zulässig, schließen wir jede Gewährleistung aus.",
    "terms.section12Title": "12. Haftungsbeschränkung",
    "terms.section12Body": "Soweit gesetzlich zulässig, haftet dolani GmbH nicht für indirekte oder Folgeschäden, Datenverlust, entgangenen Gewinn oder Umsatz. Die Gesamthaftung ist beschränkt auf die in den letzten 12 Monaten gezahlten Entgelte oder CHF 100 (der höhere Betrag gilt), sofern zwingendes Recht nichts anderes vorsieht.",
    "terms.section13Title": "13. Freistellung (B2B)",
    "terms.section13Body": "Bei Nutzung als Unternehmen stellst du dolani GmbH von Ansprüchen frei, die aus Nutzerinhalten oder Vertragsverletzungen resultieren.",
    "terms.section14Title": "14. Anwendbares Recht und Gerichtsstand",
    "terms.section14Body": "Es gilt das Recht der Schweiz. Gerichtsstand ist Zürich, soweit zwingendes Verbraucherrecht nicht entgegensteht.",
    "terms.section15Title": "15. Änderungen",
    "terms.section15Body": "Wir können die Bedingungen aktualisieren; das Datum („Stand“) weist die aktuelle Fassung aus. Fortgesetzte Nutzung gilt als Zustimmung.",
    "terms.section16Title": "16. Kontakt",
    "terms.section16Body": "dolani GmbH, Kolbenacker 14, 8052 Zürich, Schweiz. E‑Mail: compliance@dolani.ch",
    "fair.title": "Fair Use",
    "fair.subtitle": "Damit Pushcode für alle schnell und zuverlässig bleibt.",
    "fair.generalTitle": "Allgemeine Richtlinien",
    "fair.generalBody": "Pushcode ist für kurzlebige, persönliche Transfers gedacht. Bitte nutze es nicht als Massen-Hosting oder Langzeitspeicher.",
    "fair.abuseTitle": "Missbrauchsschutz",
    "fair.abuseBody": "Automatisiertes Scraping, Brute‑Force oder Missbrauch von Limits kann zu Sperren führen.",
    "fair.limitsTitle": "Angemessene Grenzen",
    "fair.limitsBody": "Wir können Uploads, Requests oder Bandbreite begrenzen, um Stabilität zu gewährleisten.",
    "privacy.title": "Datenschutzhinweise",
    "privacy.subtitle": "Datenschutzhinweise für Pushcode",
    "privacy.lastUpdated": "Stand: 20. Januar 2026",
    "privacy.section1Title": "1. Verantwortlicher",
    "privacy.controllerBody": "Verantwortlich für die Verarbeitung deiner personenbezogenen Daten ist: dolani GmbH, Kolbenacker 14, 8052 Zürich, Schweiz. E‑Mail: compliance@dolani.ch",
    "privacy.dpoBody": "Datenschutzbeauftragte/r: compliance@dolani.ch",
    "privacy.section2Title": "2. Was Pushcode ist (aus Datenschutzsicht)",
    "privacy.section2Body": "Pushcode ermöglicht Ende‑zu‑Ende verschlüsselte Dateiübertragungen über kurzlebige „Pushcodes“. Der Server speichert nur den verschlüsselten Datei‑Container („Artifact“) und wenige Metadaten, die für den Betrieb erforderlich sind. Das System ist auf Metadaten‑Minimierung ausgelegt (z. B. standardmäßig kein Dateiname/MIME im Container‑Header).",
    "privacy.section3Title": "3. Welche Daten wir verarbeiten",
    "privacy.section3A": "A. Konto‑ und Authentifizierungsdaten (registrierte Nutzer / „Owner“)",
    "privacy.section3A1": "E‑Mail‑Adresse",
    "privacy.section3A2": "Passwort‑Hash (kein Klartext‑Passwort)",
    "privacy.section3A3": "Session-/Token‑Daten (Access/Refresh‑Tokens; optional Device‑ID)",
    "privacy.section3A4": "Verifizierungsstatus und Zeitstempel",
    "privacy.section3B": "B. Pushcode‑Session & kryptografische Metadaten",
    "privacy.section3B1": "Pushcode (6 Zeichen) und Ablaufzeit (TTL)",
    "privacy.section3B2": "Owner‑Referenz (User‑ID)",
    "privacy.section3B3": "Öffentlicher Schlüssel des Empfängers (X25519 Public Key)",
    "privacy.section3B4": "Status‑Zeitstempel (Erstellung / Ablauf / Download)",
    "privacy.section3C": "C. Verschlüsselte Inhalte („Artifact“)",
    "privacy.section3C1": "Verschlüsselter Datei‑Container (Ciphertext), gespeichert bis Löschung oder Ablauf",
    "privacy.section3C2": "Container‑Header‑Elemente, die der Empfänger zur Entschlüsselung benötigt (z. B. ephemerer Public Key, wrapped key, Nonces, Dateigröße, Tag). Ohne privaten Geräteschlüssel ist daraus keine Entschlüsselung möglich.",
    "privacy.section3D": "D. Technische‑ und Sicherheitsdaten",
    "privacy.section3D1": "IP‑Adresse und Request‑Metadaten für Rate Limiting, Missbrauchsabwehr und Sicherheitsprotokollierung",
    "privacy.section3D2": "Request‑IDs / Logs (sofern aktiviert)",
    "privacy.section4Title": "4. Zwecke und Rechtsgrundlagen (DSGVO)",
    "privacy.section4A": "Bereitstellung des Dienstes (Account, Pushcodes, Übertragung) — Art. 6 Abs. 1 lit. b DSGVO",
    "privacy.section4B": "Sicherheit und Integrität — Art. 6 Abs. 1 lit. f und/oder lit. c DSGVO",
    "privacy.section4C": "Service‑Kommunikation — Art. 6 Abs. 1 lit. b und/oder lit. f DSGVO",
    "privacy.section4D": "Compliance und Rechtsdurchsetzung — Art. 6 Abs. 1 lit. f und/oder lit. c DSGVO",
    "privacy.section5Title": "5. Speicherdauer",
    "privacy.section5A": "Pushcodes & Metadaten: bis zum Ablauf (Standard 1 Stunde; konfigurierbar 5 Minuten bis 24 Stunden) oder Löschung durch den Owner.",
    "privacy.section5B": "Artifacts (verschlüsselt): bis Löschung durch den Owner, TTL‑Ablauf oder automatischer Bereinigung nach Download/Ablauf.",
    "privacy.section5C": "Kontodaten: solange das Konto aktiv ist sowie darüber hinaus, soweit gesetzlich erforderlich.",
    "privacy.section5D": "Sicherheitslogs/Rate‑Limiting: nur solange nötig (typischerweise bis zu 30 Tage).",
    "privacy.section6Title": "6. Empfänger / Auftragsverarbeiter",
    "privacy.section6A": "Hosting‑/Infrastruktur‑Dienstleister (als Auftragsverarbeiter)",
    "privacy.section6B": "E‑Mail‑Dienstleister (für Verifikation/Service‑Mails), falls eingesetzt",
    "privacy.section6C": "Behörden/Berater bei rechtlicher Verpflichtung oder zur Rechtsverteidigung",
    "privacy.section6Note": "Dateiinhalte werden nicht verkauft oder im Klartext geteilt. Der Server speichert nur verschlüsselte Artifacts; private Schlüssel verbleiben auf dem Endgerät.",
    "privacy.section7Title": "7. Drittlandtransfers",
    "privacy.section7Body": "Bei Transfers außerhalb EWR/UK/CH setzen wir erforderliche Garantien ein (z. B. Standardvertragsklauseln). Details auf Anfrage.",
    "privacy.section8Title": "8. Sicherheit",
    "privacy.section8A": "Ende‑zu‑Ende‑Verschlüsselung; private Schlüssel bleiben auf dem Gerät (Keychain/DPAPI je Plattform)",
    "privacy.section8B": "Authenticated Encryption (AES‑GCM, ChaCha20‑Poly1305)",
    "privacy.section8C": "Argon2id für Passwörter, kurzlebige Tokens",
    "privacy.section8D": "Rate Limiting gegen Pushcode‑Bruteforce",
    "privacy.section8E": "Download nur für authentifizierte Owner",
    "privacy.section9Title": "9. Deine Rechte",
    "privacy.section9Body": "Soweit gesetzlich anwendbar: Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch; Widerruf bei Einwilligung; Beschwerde bei einer Aufsichtsbehörde. Kontakt: compliance@dolani.ch.",
    "privacy.section10Title": "10. Kinder",
    "privacy.section10Body": "Pushcode richtet sich nicht an Kinder unter 16 Jahren. Wir erheben wissentlich keine Daten von Kindern.",
    "privacy.section11Title": "11. Änderungen",
    "privacy.section11Body": "Wir können diese Hinweise aktualisieren; das Datum („Stand“) zeigt den aktuellen Stand.",
    "footer.tagline": "Sicheres Teilen von Dateien für Einzelpersonen.",
    "footer.brandPrefix": "pushcode.io ist ein Produkt der",
    "footer.brandLink": "dolani GmbH",
    "footer.copyright": "© 2025 dolani GmbH - from Tsüri🇨🇭 with ❤️",
    "footer.availability": "Verfügbar für iOS, iPadOS, macOS, Windows, Linux-CLI und Web."
  },
  fr: {
    "nav.download": "Télécharger",
    "nav.how": "Comment ça marche",
    "nav.security": "Sécurité",
    "nav.platforms": "Plateformes",
    "nav.langLabel": "Langue",
    "hero.eyebrow": "Transferts rapides et privés",
    "hero.title": "Envoyez un fichier avec un code court, pas un long lien.",
    "hero.lead":
      "Pushcode rend le partage simple et sûr. Créez un code de six caractères, partagez-le et votre fichier arrive protégé. Les expéditeurs se connectent, et seul votre appareil peut l’ouvrir.",
    "hero.ctaPrimary": "Ouvrir l’app web",
    "hero.ctaSecondary": "Télécharger les apps",
    "hero.meta1Label": "Courte durée",
    "hero.meta1Value": "Les codes expirent vite",
    "hero.meta2Label": "Facile à partager",
    "hero.meta2Value": "Six caractères",
    "hero.meta3Label": "Partout",
    "hero.meta3Value": "iOS · iPadOS · macOS · Windows · Linux CLI · Web",
    "hero.status1Title": "En attente du fichier",
    "hero.status1Body": "L’expéditeur se connecte et envoie avec votre code.",
    "hero.status2Title": "Verrouillé avant l’envoi",
    "hero.status2Body": "Votre fichier reste privé du début à la fin.",
    "hero.status3Title": "Prêt quand vous l’êtes",
    "hero.status3Body": "Téléchargé une fois, puis supprimé.",
    "hero.tileLabel": "PUSHCODE ACTIF",
    "hero.tileNote": "Touchez pour copier · expire dans 58:14",
    "download.title": "Pushcode sur tous vos appareils.",
    "download.subtitle": "Téléchargez les apps pour être prêt dès qu’un fichier arrive.",
    "download.iosLabel": "iOS & iPadOS",
    "download.iosTitle": "Télécharger sur l’App Store",
    "download.iosNote": "Requiert iOS 16.6 / iPadOS 16.6+",
    "download.macLabel": "macOS",
    "download.macTitle": "Télécharger pour Mac",
    "download.macNote": "Requiert macOS 13.5 Ventura+",
    "download.winLabel": "Windows",
    "download.winTitle": "Télécharger pour Windows",
    "download.winNote": "Requiert Windows 10+",
    "download.beta": "BETA",
    "download.cta": "Télécharger",
    "download.linuxLabel": "Linux CLI",
    "download.linuxTitle": "Installer la CLI",
    "download.linuxNote": "x86_32 · amd64 · arm64",
    "download.webLabel": "Web",
    "download.webTitle": "Ouvrir dans le navigateur",
    "download.open": "Ouvrir",
    "download.webNote": "Envoi uniquement (pas de réception)",
    "download.androidLabel": "Android",
    "download.androidTitle": "Bientôt disponible",
    "download.androidNote": "Inscrivez-vous pour un accès anticipé",
    "download.select": "Sélectionner",
    "download.macSelect": "Options Mac",
    "download.macIntel": "Intel",
    "download.macApple": "Apple Silicon",
    "download.winSelect": "Options Windows",
    "download.win32": "32 bits",
    "download.win64": "64 bits",
    "download.linuxSelect": "Options Linux CLI",
    "download.linuxX86": "x86_32",
    "download.linuxAmd64": "amd64",
    "download.linuxArm64": "arm64",
    "how.title": "Fonctionnement (technique).",
    "how.subtitle":
      "L’expéditeur s’authentifie, récupère la clé publique du destinataire, chiffre localement puis envoie le conteneur chiffré. Le propriétaire télécharge et déchiffre avec sa clé d’appareil ; le serveur ne voit jamais le clair.",
    "how.step1Title": "Pushcode + clé",
    "how.step1Body": "Le propriétaire crée un pushcode lié à une clé publique d’appareil et à un TTL court.",
    "how.step2Title": "Chiffrer & envoyer",
    "how.step2Body":
      "L’expéditeur s’authentifie, récupère la clé publique, chiffre localement et envoie le conteneur chiffré.",
    "how.step3Title": "Déchiffrement propriétaire",
    "how.step3Body":
      "Le propriétaire télécharge le conteneur et déchiffre avec sa clé d’appareil ; clôture après téléchargement ou TTL.",
    "security.title": "Pensé pour la confiance.",
    "security.subtitle": "Une confidentialité simple à comprendre.",
    "security.card1Title": "Privé par défaut",
    "security.card1Body": "Les fichiers sont verrouillés avant de quitter votre appareil.",
    "security.card1Tag": "Privé",
    "security.card2Title": "Accès temporaire",
    "security.card2Body": "Les codes expirent vite, pas de vieux liens.",
    "security.card2Tag": "Court",
    "security.card3Title": "Seul le propriétaire ouvre",
    "security.card3Body": "Le fichier s’ouvre uniquement sur l’appareil qui a créé le code.",
    "security.card3Tag": "Propriétaire",
    "security.card4Title": "Protection contre le devinage",
    "security.card4Body": "Nous bloquons les tentatives répétées.",
    "security.card4Tag": "Protection",
    "security.note":
      "En bref : même si quelqu’un trouve votre code, il ne peut pas ouvrir le fichier sans votre appareil. C’est fait pour garder le privé privé.",
    "platforms.title": "Partout où vous travaillez.",
    "platforms.subtitle": "Des apps rapides et simples pour chaque appareil.",
    "platforms.iosTitle": "iOS & iPadOS",
    "platforms.iosBody": "Partage rapide avec un design mobile épuré.",
    "platforms.macTitle": "macOS",
    "platforms.macBody": "App discrète dans la barre de menus pour un accès instantané.",
    "platforms.winTitle": "Windows",
    "platforms.winBody": "Rapide, fiable, prêt pour le quotidien.",
    "platforms.linuxTitle": "Linux CLI",
    "platforms.linuxBody": "Transferts scriptables pour terminal et CI.",
    "platforms.webTitle": "Web",
    "platforms.webBody": "Utilisable partout, sans installation.",
    "api.title": "Fonctionnement (technique).",
    "api.subtitle":
      "Les fichiers sont chiffrés sur l’appareil de l’expéditeur, envoyés comme conteneurs chiffrés et ne peuvent être ouverts que par la clé de l’appareil du propriétaire.",
    "api.cardTitle": "Transferts fiables et prévisibles",
    "api.point1": "Des codes courts pour partager sans effort.",
    "api.point2": "Connexion des expéditeurs pour la traçabilité.",
    "api.point3": "Téléchargements réservés au propriétaire.",
    "api.point4": "Fonctionne sur desktop et mobile.",
    "api.cta": "Lire la doc",
    "api.noteLabel": "Description (pour lecteurs techniques)",
    "api.noteBody":
      "Pushcode est un système de transfert chiffré de bout en bout avec codes courts, connexion expéditeur et téléchargements réservés au propriétaire.",
    "cta.title": "Prêt à partager en toute confiance ?",
    "cta.subtitle": "Rejoignez la bêta privée et commencez à envoyer partout.",
    "cta.primary": "Demander l’accès",
    "cta.secondary": "Nous contacter",
    "privacy.navHome": "Accueil",
    "privacy.navPrivacy": "Confidentialité",
    "terms.navTerms": "Conditions",
    "terms.navFairUse": "Usage équitable",
    "terms.title": "Conditions d’utilisation — Pushcode",
    "terms.lastUpdated": "Dernière mise à jour : 20 janvier 2026",
    "terms.section1Title": "1. Champ d’application",
    "terms.section1Body": "Les présentes conditions (« Conditions ») régissent l’accès et l’utilisation des applications Pushcode, des API et des services associés (le « Service »). En utilisant le Service (y compris upload/download d’un artifact), vous acceptez ces Conditions.",
    "terms.section2Title": "2. Description du Service (résumé)",
    "terms.section2Body": "Pushcode permet des transferts de fichiers chiffrés de bout en bout via des pushcodes à durée de vie limitée. L’expéditeur chiffre localement et téléverse un conteneur chiffré (« artifact ») ; seul le destinataire (« Owner ») peut le télécharger et le déchiffrer.",
    "terms.section3Title": "3. Éligibilité",
    "terms.section3Body": "Vous devez avoir au moins 16 ans et la capacité juridique de contracter. Si vous utilisez le Service pour une organisation, vous déclarez être autorisé à l’engager.",
    "terms.section4Title": "4. Comptes et authentification",
    "terms.section4Body": "Les Owners créent un compte via e‑mail/mot de passe ; les mots de passe ne sont stockés qu’en tant que hash sécurisé. Le Service utilise des jetons d’accès et de rafraîchissement. Vous êtes responsable de la sécurité du compte et devez nous informer rapidement en cas d’accès non autorisé.",
    "terms.section5Title": "5. Pushcodes, modèle d’accès, limites de débit",
    "terms.section5A": "Un pushcode est un code court et temporaire (TTL par défaut 1h ; configurable).",
    "terms.section5B": "Le téléversement ne nécessite pas de connexion ; un pushcode valide agit comme jeton porteur.",
    "terms.section5C": "Le téléchargement exige l’authentification de l’Owner ; seul l’Owner peut télécharger/supprimer ses artifacts.",
    "terms.section5D": "Des limites (par IP/utilisateur) protègent contre le bruteforce et les abus.",
    "terms.section6Title": "6. Contenus, responsabilités, usage acceptable",
    "terms.section6A": "Vous êtes responsable des contenus envoyés/reçus (« Contenu Utilisateur »).",
    "terms.section6B": "Usages interdits : illégalité, atteinte aux droits, malware/phishing/spam, deviner des pushcodes, contourner les limites ou perturber le Service.",
    "terms.section6C": "Évitez de téléverser des données hautement sensibles si vous n’acceptez pas les risques liés aux terminaux et aux clés.",
    "terms.section7Title": "7. Chiffrement, clés, limites de confidentialité",
    "terms.section7A": "AES‑256‑GCM pour le fichier ; key wrap via X25519 + HKDF‑SHA256 + ChaCha20‑Poly1305.",
    "terms.section7B": "La perte de la clé privée peut rendre l’accès aux artifacts définitivement impossible.",
    "terms.section7C": "Nous ne déchiffrons pas les artifacts en fonctionnement normal ; la confidentialité dépend aussi de la sécurité de votre appareil.",
    "terms.section8Title": "8. Limites, stockage, disponibilité",
    "terms.section8A": "Limite de taille (MVP : 100MB max par artifact).",
    "terms.section8B": "Pushcodes/artifacts expirent selon TTL et cycle de vie ; suppression automatique possible.",
    "terms.section8C": "Le Service peut être modifié/suspendu ; aucune disponibilité continue n’est garantie.",
    "terms.section9Title": "9. Propriété intellectuelle",
    "terms.section9Body": "Le Service et ses éléments sont la propriété de dolani GmbH ou de ses concédants. Vous disposez d’une licence limitée d’utilisation conforme aux présentes Conditions.",
    "terms.section10Title": "10. Suspension / résiliation",
    "terms.section10Body": "Vous pouvez cesser d’utiliser le Service à tout moment. Nous pouvons suspendre/résilier en cas de violation, d’obligation légale, ou pour protéger le Service et les utilisateurs.",
    "terms.section11Title": "11. Exclusion de garanties",
    "terms.section11Body": "Le Service est fourni « tel quel » et « selon disponibilité ». Dans la mesure autorisée par la loi, nous excluons toute garantie.",
    "terms.section12Title": "12. Limitation de responsabilité",
    "terms.section12Body": "Dans la mesure autorisée par la loi, dolani GmbH n’est pas responsable des dommages indirects, perte de données, profits ou chiffre d’affaires. La responsabilité totale est limitée aux montants payés sur les 12 derniers mois ou à CHF 100 (le plus élevé), sauf droit impératif contraire.",
    "terms.section13Title": "13. Indemnisation (B2B)",
    "terms.section13Body": "Si vous utilisez le Service à titre professionnel, vous acceptez d’indemniser dolani GmbH pour les réclamations liées à votre Contenu Utilisateur ou à la violation des présentes.",
    "terms.section14Title": "14. Droit applicable et juridiction",
    "terms.section14Body": "Les présentes sont régies par le droit suisse. Juridiction compétente : Zurich, sous réserve du droit impératif des consommateurs.",
    "terms.section15Title": "15. Modifications",
    "terms.section15Body": "Nous pouvons mettre à jour ces Conditions ; la date de mise à jour indique la version en vigueur. L’utilisation continue vaut acceptation.",
    "terms.section16Title": "16. Contact",
    "terms.section16Body": "dolani GmbH, Kolbenacker 14, 8052 Zurich, Suisse. E‑mail : compliance@dolani.ch",
    "fair.title": "Usage équitable",
    "fair.subtitle": "Pour garder Pushcode rapide et fiable pour tous.",
    "fair.generalTitle": "Principes généraux",
    "fair.generalBody": "Pushcode est pensé pour des transferts courts et personnels. Évitez de l’utiliser comme stockage longue durée.",
    "fair.abuseTitle": "Prévention des abus",
    "fair.abuseBody": "Le scraping automatisé, le brute‑force ou l’abus des limites peut entraîner des blocages.",
    "fair.limitsTitle": "Limites raisonnables",
    "fair.limitsBody": "Nous pouvons limiter les uploads, requêtes ou la bande passante pour la stabilité du service.",
    "privacy.title": "Informations de confidentialité",
    "privacy.subtitle": "Informations de confidentialité pour Pushcode",
    "privacy.lastUpdated": "Dernière mise à jour : 20 janvier 2026",
    "privacy.section1Title": "1. Responsable du traitement",
    "privacy.controllerBody": "Le responsable du traitement est : dolani GmbH, Kolbenacker 14, 8052 Zurich, Suisse. E‑mail : compliance@dolani.ch",
    "privacy.dpoBody": "Délégué(e) à la protection des données (DPO) : compliance@dolani.ch",
    "privacy.section2Title": "2. Pushcode en bref (angle vie privée)",
    "privacy.section2Body": "Pushcode permet des transferts de fichiers chiffrés de bout en bout via des « pushcodes » à durée de vie limitée. Le serveur ne conserve que le conteneur chiffré (« artifact ») et des métadonnées minimales nécessaires au fonctionnement. La conception vise la minimisation des métadonnées (par défaut, pas de nom de fichier ni de type MIME dans l’en‑tête du conteneur).",
    "privacy.section3Title": "3. Données personnelles traitées",
    "privacy.section3A": "A. Données de compte et d’authentification (utilisateurs enregistrés / “owner”)",
    "privacy.section3A1": "Adresse e‑mail",
    "privacy.section3A2": "Empreinte (hash) du mot de passe (aucun mot de passe en clair)",
    "privacy.section3A3": "Données de session / jetons (access/refresh tokens ; identifiant d’appareil si fourni)",
    "privacy.section3A4": "Statut de vérification e‑mail et horodatages",
    "privacy.section3B": "B. Session pushcode & métadonnées cryptographiques",
    "privacy.section3B1": "Pushcode (6 caractères) et date d’expiration (TTL)",
    "privacy.section3B2": "Référence du propriétaire (user ID)",
    "privacy.section3B3": "Clé publique du destinataire (clé publique X25519)",
    "privacy.section3B4": "Horodatages d’état (création / expiration / téléchargement)",
    "privacy.section3C": "C. Contenu chiffré (“artifact”)",
    "privacy.section3C1": "Conteneur chiffré (ciphertext) stocké jusqu’à suppression ou expiration",
    "privacy.section3C2": "Éléments d’en‑tête nécessaires au déchiffrement côté destinataire (ex. clé publique éphémère, clé “wrapped”, nonces, taille, tag). Ils ne permettent pas le déchiffrement sans la clé privée du destinataire.",
    "privacy.section3D": "D. Données techniques et de sécurité",
    "privacy.section3D1": "Adresse IP et métadonnées de requête (rate limiting, prévention des abus, journalisation sécurité)",
    "privacy.section3D2": "Identifiants de requête / logs (si activés)",
    "privacy.section4Title": "4. Finalités et bases légales (RGPD)",
    "privacy.section4A": "Fourniture du service (compte, pushcodes, transfert) — art. 6(1)(b) RGPD",
    "privacy.section4B": "Sécurité et intégrité — art. 6(1)(f) et/ou 6(1)(c) RGPD",
    "privacy.section4C": "Communications de service — art. 6(1)(b) et/ou 6(1)(f)",
    "privacy.section4D": "Conformité et défense en justice — art. 6(1)(f) et/ou 6(1)(c)",
    "privacy.section5Title": "5. Durées de conservation",
    "privacy.section5A": "Pushcodes & métadonnées associées : jusqu’à expiration (TTL par défaut 1h ; configurable 5 min–24h) ou suppression par le propriétaire.",
    "privacy.section5B": "Artifacts chiffrés : jusqu’à suppression, expiration TTL ou nettoyage après téléchargement/expiration.",
    "privacy.section5C": "Données de compte : tant que le compte est actif et selon les obligations légales.",
    "privacy.section5D": "Logs sécurité / rate limiting : durée nécessaire à la protection du service (généralement jusqu’à 30 jours).",
    "privacy.section6Title": "6. Destinataires",
    "privacy.section6A": "Fournisseurs d’hébergement et d’infrastructure (sous‑traitants)",
    "privacy.section6B": "Prestataires e‑mail (vérification / e‑mails de service), le cas échéant",
    "privacy.section6C": "Autorités / conseils lorsque requis ou nécessaire",
    "privacy.section6Note": "Nous ne vendons pas le contenu des fichiers. Le serveur ne conserve que des artifacts chiffrés ; les clés privées restent sur l’appareil.",
    "privacy.section7Title": "7. Transferts internationaux",
    "privacy.section7Body": "En cas de transfert hors EEE/UK/Suisse, nous mettons en place les garanties appropriées (p. ex. clauses contractuelles types). Détails sur demande.",
    "privacy.section8Title": "8. Sécurité",
    "privacy.section8A": "Conception bout‑en‑bout : clés privées sur l’appareil",
    "privacy.section8B": "Chiffrement authentifié (AES‑GCM, ChaCha20‑Poly1305)",
    "privacy.section8C": "Hashage robuste des mots de passe (Argon2id), jetons à durée courte",
    "privacy.section8D": "Rate limiting anti‑bruteforce des pushcodes",
    "privacy.section8E": "Téléchargement réservé au propriétaire authentifié",
    "privacy.section9Title": "9. Vos droits",
    "privacy.section9Body": "Selon la loi applicable : accès, rectification, effacement, limitation, portabilité, opposition, retrait du consentement et réclamation auprès d’une autorité de contrôle. Contact : compliance@dolani.ch.",
    "privacy.section10Title": "10. Enfants",
    "privacy.section10Body": "Pushcode n’est pas destiné aux enfants de moins de 16 ans. Nous ne collectons pas sciemment leurs données.",
    "privacy.section11Title": "11. Modifications",
    "privacy.section11Body": "Nous pouvons mettre à jour ces informations ; la date de mise à jour indiquera la version en vigueur.",
    "footer.tagline": "Partage de fichiers sécurisé pour les particuliers.",
    "footer.brandPrefix": "pushcode.io est un produit de",
    "footer.brandLink": "dolani GmbH",
    "footer.copyright": "© 2025 dolani GmbH - from Tsüri🇨🇭 with ❤️",
    "footer.availability": "Disponible sur iOS, iPadOS, macOS, Windows, Linux CLI et web."
  }
};

const i18nElements = document.querySelectorAll("[data-i18n]");
const i18nTitleElements = document.querySelectorAll("[data-i18n-title]");
const i18nAriaElements = document.querySelectorAll("[data-i18n-aria]");
const languageSelect = document.querySelector("#lang-select");

const setLanguage = (lang) => {
  const pack = translations[lang] || translations.en;
  i18nElements.forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (pack[key]) {
      el.textContent = pack[key];
    }
  });
  i18nTitleElements.forEach((el) => {
    const key = el.getAttribute("data-i18n-title");
    if (pack[key]) {
      el.setAttribute("title", pack[key]);
      el.setAttribute("aria-label", pack[key]);
    }
  });
  i18nAriaElements.forEach((el) => {
    const key = el.getAttribute("data-i18n-aria");
    if (pack[key]) {
      el.setAttribute("aria-label", pack[key]);
    }
  });
  document.documentElement.lang = lang;
  if (languageSelect) {
    languageSelect.value = lang;
  }
  localStorage.setItem("pushcode-lang", lang);
};

const savedLang = localStorage.getItem("pushcode-lang");
const browserLang = navigator.language ? navigator.language.slice(0, 2) : "en";
const defaultLang = savedLang || (translations[browserLang] ? browserLang : "en");
setLanguage(defaultLang);

if (languageSelect) {
  languageSelect.addEventListener("change", (event) => {
    setLanguage(event.target.value);
  });
}

const dropdowns = document.querySelectorAll("[data-dropdown]");

const closeAllDropdowns = () => {
  dropdowns.forEach((dropdown) => {
    dropdown.classList.remove("open");
    const toggle = dropdown.querySelector(".dropdown-toggle");
    if (toggle) toggle.setAttribute("aria-expanded", "false");
  });
};

dropdowns.forEach((dropdown) => {
  const toggle = dropdown.querySelector(".dropdown-toggle");
  const items = dropdown.querySelectorAll(".dropdown-item");

  if (toggle) {
    toggle.addEventListener("click", (event) => {
      event.stopPropagation();
      const isOpen = dropdown.classList.contains("open");
      closeAllDropdowns();
      if (!isOpen) {
        dropdown.classList.add("open");
        toggle.setAttribute("aria-expanded", "true");
      }
    });
  }

  items.forEach((item) => {
    item.addEventListener("click", () => {
      closeAllDropdowns();
    });
  });
});

document.addEventListener("click", closeAllDropdowns);
document.addEventListener("keydown", (event) => {
  if (event.key === "Escape") {
    closeAllDropdowns();
  }
});

const downloadSelects = document.querySelectorAll(".download-select");
downloadSelects.forEach((select) => {
  select.addEventListener("change", (event) => {
    event.target.selectedIndex = 0;
  });
});
